# Generated by Django 3.0.5 on 2020-09-13 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0003_coffemachine_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='coffemachine',
            name='name',
            field=models.CharField(default='', max_length=70),
        ),
        migrations.AddField(
            model_name='coffepods',
            name='name',
            field=models.CharField(default='', max_length=70),
        ),
        migrations.AlterField(
            model_name='coffemachine',
            name='water_line_compatible',
            field=models.BooleanField(),
        ),
    ]
